# Generated by Django 4.1.3 on 2022-11-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVNSweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readings',
            new_name='Reading',
        ),
    ]
