# Generated by Django 4.1.3 on 2022-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVNSweb', '0002_rename_readings_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='plate_number',
            field=models.CharField(default='ABC1234', max_length=20, verbose_name='Plate No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reading',
            name='db_reading',
            field=models.IntegerField(verbose_name='dB'),
        ),
    ]
